### ISSUE TITLE
License missing in source distribution

### ISSUE THREAD

**Issue by kynan** [davidmegginson/python-io-wrapper#1]
The [license file](https://github.com/davidmegginson/python-io-wrapper/blob/main/UNLICENSE.md) is unfortunately not packaged in the [source distribution](https://files.pythonhosted.org/packages/ac/d0/7fd94fc5f649ba1dd3f73a56abaa09bfedcd28b4ef1647f2645ce507c10f/python-io-wrapper-0.2.tar.gz) on [PyPI](https://pypi.org/project/python-io-wrapper), which prevents me from packaging this package for conda-forge. Could you please cut a new release that includes `UNLICENSE.md` in the source distribution?

**Comment by davidmegginson** [comment]
Will do. PyPi is still a bit of a mystery to me, so I'll try to figure out why it didn't get picked up 5 years ago.

**Comment by kynan** [comment]
Thanks!
